export type Specimen = { id: string; category: 'organic' | 'inorganic'; code: string; name: string; hex: string; };

export const SPECIMEN_DATA: Specimen[] = [
  // ORGANIC
  { id: '1', category: 'organic', code: 'PV23', name: 'Royal Glass Violet', hex: '#1A0B2E' },
  { id: '2', category: 'organic', code: 'PG7', name: 'Emerald Nano', hex: '#003D1A' },
  { id: '3', category: 'organic', code: 'PY184', name: 'Solar Flare Yellow', hex: '#FFC800' },
  { id: '4', category: 'organic', code: 'PR179', name: 'Bordeaux Depth', hex: '#3B0008' },
  { id: '5', category: 'organic', code: 'PY128', name: 'Acidic Glass Yellow', hex: '#E5E600' },
  { id: '6', category: 'organic', code: 'PBk27', name: 'The Bluest Black', hex: '#030811' },
  { id: '7', category: 'organic', code: 'PBr7', name: 'The Earth Soul', hex: '#2A140F' },
  { id: '8', category: 'organic', code: 'PR233', name: 'The Cult Pink', hex: '#BC878E' },
  { id: '9', category: 'organic', code: 'PB15:3', name: 'Nano Cyan', hex: '#004A75' },
  { id: '10', category: 'organic', code: 'PB16', name: 'Crystalline Turquoise', hex: '#006166' },
  { id: '11', category: 'organic', code: 'PB15:6', name: 'Epsilon Blue', hex: '#0A1838' },
  { id: '12', category: 'organic', code: 'PBk31', name: 'The Void Black', hex: '#060906' },
  { id: '13', category: 'organic', code: 'PBk32', name: 'Shadow Black', hex: '#050D08' },
  { id: '14', category: 'organic', code: 'PR264', name: 'The Ruby', hex: '#63000E' },
  { id: '15', category: 'organic', code: 'PO71', name: 'The Fire', hex: '#BA2A00' },
  { id: '16', category: 'organic', code: 'PY150', name: 'The Glow', hex: '#B87E00' },
  { id: '17', category: 'organic', code: 'PR254', name: 'Ferrari Red', hex: '#9E0000' },
  { id: '18', category: 'organic', code: 'PR122', name: 'Primary Magenta', hex: '#A3004C' },
  { id: '19', category: 'organic', code: 'PW6 (NANO)', name: 'The Ghost', hex: '#D1D5DF' },
  { id: '20', category: 'organic', code: 'PV19', name: 'The Shadow', hex: '#4A0021' },
  { id: '21', category: 'organic', code: 'PG36', name: 'Hyper-Green', hex: '#007A23' },
  { id: '22', category: 'organic', code: 'PR101', name: 'Earth Light', hex: '#591C0B' },
  { id: '23', category: 'organic', code: 'PY42', name: 'Liquid Gold', hex: '#8F570B' },
  { id: '24', category: 'organic', code: 'PB60', name: 'Indanthrone Midnight', hex: '#070D1F' },
  // INORGANIC
  { id: '25', category: 'inorganic', code: 'PW5', name: 'The Scalar Ghost', hex: '#EBEBCE' },
  { id: '26', category: 'inorganic', code: 'PW7', name: 'The Scalar Lume', hex: '#F0F0F0' },
  { id: '27', category: 'inorganic', code: 'PW6', name: 'Primary White', hex: '#FFFFFF' },
  { id: '28', category: 'inorganic', code: 'PB36', name: 'IR-Reflecting Turquoise', hex: '#004952' },
  { id: '29', category: 'inorganic', code: 'PB28', name: 'Pure Physics Blue', hex: '#142054' },
  { id: '30', category: 'inorganic', code: 'PY53', name: 'Primrose Yellow', hex: '#CFCA65' },
  { id: '31', category: 'inorganic', code: 'PG17', name: 'Cool Roof Olive', hex: '#31422A' },
  { id: '32', category: 'inorganic', code: 'PV15', name: 'Ultramarine Violet', hex: '#261540' },
  { id: '33', category: 'inorganic', code: 'PR259', name: 'Ultramarine Pink', hex: '#9E6D7D' },
  { id: '34', category: 'inorganic', code: 'MAGNETITE', name: 'Chromatic Black', hex: '#0E0E0E' },
  { id: '35', category: 'inorganic', code: 'PG50', name: 'Cobalt Titanate Green', hex: '#002E1D' },
];
