export type Specimen = { id: string; category: 'organic' | 'inorganic'; code: string; name: string; chemicalName: string; hex: string; };

export const SPECIMEN_DATA: Specimen[] = [
  // ORGANIC
  { id: '1', category: 'organic', code: 'PV23', name: 'Royal Glass Violet', chemicalName: 'DIOXAZINE VIOLET', hex: '#1A0B2E' },
  { id: '2', category: 'organic', code: 'PG7', name: 'Emerald Nano', chemicalName: 'PHTHALOCYANINE GREEN', hex: '#003D1A' },
  { id: '3', category: 'organic', code: 'PY184', name: 'Solar Flare Yellow', chemicalName: 'BISMUTH VANADATE', hex: '#FFC800' },
  { id: '4', category: 'organic', code: 'PR179', name: 'Bordeaux Depth', chemicalName: 'PERYLENE MAROON', hex: '#3B0008' },
  { id: '5', category: 'organic', code: 'PY128', name: 'Acidic Glass Yellow', chemicalName: 'AZO CONDENSATION YELLOW', hex: '#E5E600' },
  { id: '6', category: 'organic', code: 'PBk27', name: 'The Bluest Black', chemicalName: 'IRON COBALT CHROMITE', hex: '#030811' },
  { id: '7', category: 'organic', code: 'PBr7', name: 'The Earth Soul', chemicalName: 'NATURAL IRON OXIDE', hex: '#2A140F' },
  { id: '8', category: 'organic', code: 'PR233', name: 'The Cult Pink', chemicalName: 'CHROME TIN PINK', hex: '#BC878E' },
  { id: '9', category: 'organic', code: 'PB15:3', name: 'Nano Cyan', chemicalName: 'PHTHALOCYANINE BLUE GS', hex: '#004A75' },
  { id: '10', category: 'organic', code: 'PB16', name: 'Crystalline Turquoise', chemicalName: 'METAL-FREE PHTHALO', hex: '#006166' },
  { id: '11', category: 'organic', code: 'PB15:6', name: 'Epsilon Blue', chemicalName: 'PHTHALOCYANINE BLUE RS', hex: '#0A1838' },
  { id: '12', category: 'organic', code: 'PBk31', name: 'The Void Black', chemicalName: 'PERYLENE BLACK', hex: '#060906' },
  { id: '13', category: 'organic', code: 'PBk32', name: 'Shadow Black', chemicalName: 'PERYLENE GREEN', hex: '#050D08' },
  { id: '14', category: 'organic', code: 'PR264', name: 'The Ruby', chemicalName: 'PYRROLO PYRROLE RUBY', hex: '#63000E' },
  { id: '15', category: 'organic', code: 'PO71', name: 'The Fire', chemicalName: 'TRANSPARENT PYRROLE ORANGE', hex: '#BA2A00' },
  { id: '16', category: 'organic', code: 'PY150', name: 'The Glow', chemicalName: 'NICKEL AZO YELLOW', hex: '#B87E00' },
  { id: '17', category: 'organic', code: 'PR254', name: 'Ferrari Red', chemicalName: 'PYRROLE RED', hex: '#9E0000' },
  { id: '18', category: 'organic', code: 'PR122', name: 'Primary Magenta', chemicalName: 'QUINACRIDONE MAGENTA', hex: '#A3004C' },
  { id: '19', category: 'organic', code: 'PW6 (NANO)', name: 'The Ghost', chemicalName: 'TITANIUM DIOXIDE NANO', hex: '#D1D5DF' },
  { id: '20', category: 'organic', code: 'PV19', name: 'The Shadow', chemicalName: 'QUINACRIDONE VIOLET', hex: '#4A0021' },
  { id: '21', category: 'organic', code: 'PG36', name: 'Hyper-Green', chemicalName: 'PHTHALOCYANINE GREEN YS', hex: '#007A23' },
  { id: '22', category: 'organic', code: 'PR101', name: 'Earth Light', chemicalName: 'SYNTHETIC IRON OXIDE RED', hex: '#591C0B' },
  { id: '23', category: 'organic', code: 'PY42', name: 'Liquid Gold', chemicalName: 'SYNTHETIC IRON OXIDE YELLOW', hex: '#8F570B' },
  { id: '24', category: 'organic', code: 'PB60', name: 'Indanthrone Midnight', chemicalName: 'INDANTHRONE BLUE', hex: '#070D1F' },
  // INORGANIC
  { id: '25', category: 'inorganic', code: 'PW5', name: 'The Scalar Ghost', chemicalName: 'LITHOPONE', hex: '#EBEBCE' },
  { id: '26', category: 'inorganic', code: 'PW7', name: 'The Scalar Lume', chemicalName: 'ZINC SULFIDE', hex: '#F0F0F0' },
  { id: '27', category: 'inorganic', code: 'PW6', name: 'Primary White', chemicalName: 'TITANIUM DIOXIDE', hex: '#FFFFFF' },
  { id: '28', category: 'inorganic', code: 'PB36', name: 'IR-Reflecting Turquoise', chemicalName: 'COBALT CHROMITE BLUE', hex: '#004952' },
  { id: '29', category: 'inorganic', code: 'PB28', name: 'Pure Physics Blue', chemicalName: 'COBALT ALUMINATE BLUE', hex: '#142054' },
  { id: '30', category: 'inorganic', code: 'PY53', name: 'Primrose Yellow', chemicalName: 'NICKEL ANTIMONY TITANIUM', hex: '#CFCA65' },
  { id: '31', category: 'inorganic', code: 'PG17', name: 'Cool Roof Olive', chemicalName: 'CHROMIUM OXIDE GREEN', hex: '#31422A' },
  { id: '32', category: 'inorganic', code: 'PV15', name: 'Ultramarine Violet', chemicalName: 'ULTRAMARINE VIOLET', hex: '#261540' },
  { id: '33', category: 'inorganic', code: 'PR259', name: 'Ultramarine Pink', chemicalName: 'ULTRAMARINE PINK', hex: '#9E6D7D' },
  { id: '34', category: 'inorganic', code: 'MAGNETITE', name: 'Chromatic Black', chemicalName: 'MAGNETITE BLACK IRON', hex: '#0E0E0E' },
  { id: '35', category: 'inorganic', code: 'PG50', name: 'Cobalt Titanate Green', chemicalName: 'COBALT TITANATE GREEN', hex: '#002E1D' },
];
